### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by NetherFossil** [PopcornColonell/hypnosource#4]
All my other apps are fine, they can play audio, but only hypno bein mute. i checked the files and they had sound but it still wont play when I run the game

**Comment by ralfslapins** [comment]
press numpad 0 or numpad +
for some reason, lullaby is muted by default

**Comment by REALHaydenGaming** [comment]
hl has audio muted for a creepy effect;

press 0, +, or numpad.

**Comment by NetherFossil** [comment]
k thanks
